name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            action/frontend/package-lock.json

      - name: Detect repository info and set BASE_PATH
        id: detect
        shell: bash
        run: |
          REPO_FULL="$GITHUB_REPOSITORY"   # e.g. username/repo or username/username.github.io
          OWNER="${REPO_FULL%%/*}"
          REPO="${REPO_FULL##*/}"

          if [[ "$REPO" == "${OWNER}.github.io" ]]; then
            echo "Detected user/organization site. BASE_PATH will be empty."
            echo "BASE_PATH=" >> $GITHUB_OUTPUT
          else
            echo "Detected project site. BASE_PATH will be /$REPO."
            echo "BASE_PATH=/$REPO" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies (frontend)
        working-directory: action/frontend
        run: npm ci

      - name: Build static site with Next.js export
        working-directory: action/frontend
        env:
          # next.config.ts reads this to set basePath/assetPrefix
          BASE_PATH: ${{ steps.detect.outputs.BASE_PATH }}
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: action/frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


